fix: talib installation

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -25,21 +25,27 @@ RUN apt-get update && apt-get install -y \
     automake \
     autoconf \
     libtool \
+    dpkg-dev \
     && rm -rf /var/lib/apt/lists/*
 
-RUN curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz | tar xz && \
-    cd ta-lib && \
-    ./configure --build=x86_64-pc-linux-gnu --prefix=/usr/local --enable-shared && \
-    make && make install && \
-    ln -s /usr/local/lib/libta_lib.so /usr/local/lib/libta-lib.so && \
-    ln -s /usr/local/lib/libta_lib.a /usr/local/lib/libta-lib.a && \
-    cd .. && rm -rf ta-lib
+RUN wget https://github.com/TA-Lib/ta-lib/releases/download/v0.6.1/ta-lib-0.6.1-src.tar.gz && \
+    tar -xzf ta-lib-0.6.1-src.tar.gz && \
+    cd ta-lib-0.6.1 && \
+    ./configure --prefix=/usr/local --enable-shared && \
+    make && make install
 
 ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 ENV LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
 ENV CPATH=/usr/local/include:$CPATH
 
+# Install Python wrapper
+RUN python3 -m pip install --no-cache-dir ta-lib
+
+# Optional: Verify symbol
+RUN nm -D /usr/local/lib/libta_lib.so | grep TA_AVGDEV_Lookback || echo "Symbol not found"
+
+# Install other Python packages
 RUN pip install --upgrade pip
-RUN pip install vectorbt TA-Lib
+RUN pip install vectorbt
 
 WORKDIR /workspace
